import PageHero from '../components/PageHero.jsx'
import Reveal from '../components/Reveal.jsx'
import AboutSection from '../components/About.jsx'
import MissionVision from '../components/MissionVision.jsx'
import StatsBand from '../components/StatsBand.jsx'
import { images } from '../components/assets.js'

const TIMELINE = [
  {
    year: '2002',
    title: 'Incorporation',
    text: 'HKAP Limited is incorporated in Nigeria on 6 November 2002 under RC Number 464616, in accordance with the Companies Act 1990.',
  },
  {
    year: '2002+',
    title: 'Recycling leadership',
    text: 'Building a One-Stop-Centre on a Total Waste Management concept — scrap collection, metal smelting and waste handling and disposal.',
  },
  {
    year: 'Growth',
    title: 'Oil & gas capability',
    text: 'Managing scrap generated by the oil and gas industry builds deep technical understanding of the sector and its operational standards.',
  },
  {
    year: '2019',
    title: 'TIKVAH acquisition',
    text: 'HKAP acquires the TIKVAH heavy-duty swamp barge drilling rig — formerly Lonestar 203 / Pride of Africa — through transparent, competitive bidding, with a clean, unencumbered title.',
  },
  {
    year: 'Today',
    title: 'Integrated energy & recycling',
    text: 'Six service lines served by a multi-disciplinary leadership team and technical workforce — chartered to NNPCL, Seplat Energy and Sahara Energy.',
  },
]

export default function AboutPage() {
  return (
    <>
      <PageHero
        kicker="Company Profile"
        title="About"
        accent="HKAP"
        sub="A Nigerian integrated industrial company — more than two decades of recycling, waste management and upstream oil and gas capability."
        image={images.purpose}
      />

      <AboutSection />

      <StatsBand
        data={[
          { to: 2002, suffix: '', label: 'Incorporated', group: false },
          { to: 24, suffix: '+', label: 'Years in Business' },
          { to: 464616, suffix: '', label: 'RC Number' },
          { to: 100, suffix: '%', label: 'Nigerian Owned' },
        ]}
      />

      <section id="history" className="section section--tint">
        <div className="container">
          <div className="sec-head">
            <Reveal>
              <span className="kicker">Our Journey</span>
              <h2 className="sec-title">
                A history of <span className="serif">steady growth</span>
              </h2>
            </Reveal>
          </div>

          <div>
            {TIMELINE.map((t, i) => (
              <Reveal key={t.year} delay={i * 60}>
                <div className="timeline__row">
                  <div className="timeline__year">{t.year}</div>
                  <div className="timeline__body">
                    <h3>{t.title}</h3>
                    <p>{t.text}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      <div className="section">
        <div className="container">
          <div className="sec-head sec-head--center">
            <Reveal>
              <span className="kicker">Governance</span>
              <h2 className="sec-title">
                Built on <span className="serif">ethics</span>
              </h2>
            </Reveal>
          </div>
          <Reveal>
            <p style={{ maxWidth: '760px', margin: '0 auto', textAlign: 'center', color: 'var(--muted)', lineHeight: 1.9 }}>
              HKAP Limited is supported by an experienced management team and a
              technical workforce guided by strong corporate governance and
              professional ethics. Client satisfaction and sustainable
              industrial excellence remain the benchmark of everything we do —
              from the scrapyard to the wellsite.
            </p>
          </Reveal>
        </div>
      </div>

      <MissionVision />
    </>
  )
}