import PageHero from '../components/PageHero.jsx'
import Reveal from '../components/Reveal.jsx'
import Services from '../components/Services.jsx'
import Icon from '../components/icons.jsx'
import { Link } from 'react-router-dom'
import { images } from '../components/assets.js'

const RECYCLING_POINTS = [
  'Scrap collection with nationwide coverage',
  'Metal smelting and processing',
  'Waste handling and industrial disposal',
  'Reduced cost and management time for clients',
]

const RIG_SVC_POINTS = [
  'Drilling operations — vertical & horizontal wells',
  'Long-term swamp barge rig charter',
  'Well control, drilling fluids and technical support',
  'Marine logistics and helideck coordination',
]

export default function ServicesPage() {
  return (
    <>
      <PageHero
        kicker="What We Do"
        title="Our"
        accent="Services"
        sub="Six industrial and energy service lines — from upstream drilling to metal recycling — delivered by one accountable partner with 24+ years of experience."
        image={images.drilling}
      />

      <Services cardTo="/contact" />

      <section className="section section--tint">
        <div className="container">
          <div className="row-split">
            <Reveal variant="left">
              <div className="row-split__media">
                <img src={images.downhole} alt="Metal scrap and recycling" loading="lazy" decoding="async" />
              </div>
            </Reveal>

            <Reveal variant="right" delay={120}>
              <span className="kicker">Recycling Division</span>
              <h3 className="row-split__title">
                Total Waste Management — a true <span className="serif">One-Stop-Centre</span>
              </h3>
              <p>
                Our recycling division manages scrap and waste professionally,
                so clients avoid unnecessary cost and, where possible, increase
                revenue. Experience gained across two decades — including scrap
                generated by the oil and gas industry — underpins our handling
                standards.
              </p>
              <ul className="chip-list">
                {RECYCLING_POINTS.map((p) => (
                  <li key={p}>
                    <Icon name="check" size={16} />
                    {p}
                  </li>
                ))}
              </ul>
              <div className="row-split__cta">
                <Link className="btn btn--ink" to="/contact">
                  Discuss a Recycling Programme
                  <span className="btn__ic">
                    <Icon name="arrow" size={17} />
                  </span>
                </Link>
              </div>
            </Reveal>
          </div>

          <div className="row-split row-split--flip">
            <Reveal variant="right" delay={120}>
              <div className="row-split__media">
                <img src={images.rig} alt="TIKVAH drilling rig services" loading="lazy" decoding="async" />
              </div>
            </Reveal>

            <Reveal variant="left">
              <span className="kicker">Upstream Division</span>
              <h3 className="row-split__title">
                Rig leasing &amp; drilling <span className="serif">operations</span>
              </h3>
              <p>
                Centred on the TIKVAH — a heavy-duty swamp barge drilling rig
                with a 20,000 ft depth rating — our upstream division provides
                drilling capability for the riverine and shallow-water
                environments of the Niger Delta.
              </p>
              <ul className="chip-list">
                {RIG_SVC_POINTS.map((p) => (
                  <li key={p}>
                    <Icon name="check" size={16} />
                    {p}
                  </li>
                ))}
              </ul>
              <div className="row-split__cta"></div>
            </Reveal>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="team__note" style={{ maxWidth: '900px', margin: '0 auto' }}>
            <strong style={{ color: 'var(--ink-900)' }}>Quality, Health, Safety &amp; Environment.</strong>{' '}
            Every service is delivered to the highest standard of safety — with
            crew certified in IADC rig operations, IWCF well control, offshore
            survival and confined space working.
          </div>
        </div>
      </section>
    </>
  )
}