import { images } from './assets.js'
import Reveal from './Reveal.jsx'
import Counter from './Counter.jsx'

const BADGES = ['RC 464616', 'Incorporated 2002', '24+ Years', 'IADC Practices']

export default function About() {
  return (
    <section id="about" className="section">
      <div className="container">
        <div className="about__grid">
          <Reveal variant="left">
            <div className="about__media">
              <img src={images.about} alt="HKAP Limited operations" />
              <div className="about__float">
                <b>
                  <Counter to={2002} duration={1400} />
                </b>
                <span>Established</span>
              </div>
            </div>
          </Reveal>

          <Reveal variant="right" delay={120}>
            <div className="about__body">
              <span className="kicker">Who We Are</span>
              <h2 className="sec-title">
                Two decades of industry, <span className="serif">one standard.</span>
              </h2>
              <p>
                <strong>HKAP Limited</strong> was incorporated in Nigeria on 6
                November 2002, under RC Number 464616, in accordance with the
                Companies Act 1990. For more than two decades the company has
                grown within the recycling industry — managing scrap and waste
                professionally so clients avoid unnecessary cost and, wherever
                possible, increase revenue.
              </p>
              <p>
                Our <strong>One-Stop-Centre</strong>, built on a Total Waste
                Management concept, covers scrap collection, metal smelting and
                waste handling and disposal. That depth of experience — including
                scrap generated by the oil and gas industry — translated directly
                into the technical capability now deployed to operate our own
                drilling rig, the TIKVAH.
              </p>
              <blockquote className="about__quote">
                From the scrapyard to the wellsite — capability built over 24
                years under one roof.
              </blockquote>
              <div className="about__badges">
                {BADGES.map((b) => (
                  <span className="about__badge" key={b}>
                    {b}
                  </span>
                ))}
              </div>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  )
}